[project]
name = "blank-skill"
version = "0.1.0"
description = "A template for a skill that can be published to the Composabl UI"
authors = [{ name = "John Doe", email = "john.doe@composabl.com" }]
dependencies = [
    "composabl-core"
]

[composabl]
type = "skill-teacher"
entrypoint = "blank_skill.teacher:Teacher"
